name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create directories
      run: |
        mkdir -p $AIRFLOW_HOME/dags/data/raw  # Crear la carpeta si no existe
      env:
        AIRFLOW_HOME: ${{ github.workspace }}/ecobici  # Definir AIRFLOW_HOME

    - name: Run tests
      env:
        AIRFLOW_HOME: ${{ github.workspace }}/ecobici
        vclient_id: ${{ secrets.VCLIENT_ID }}
        vclient_secret: ${{ secrets.VCLIENT_SECRET }}
      run: |
        python -m unittest discover -s tests
